<?php
$tours = [
  [
    'slug'        => 'ricks-cafe-sunset',
    'name'        => "Rick's Café Sunset & Cliff Diving",
    'category'    => 'nightlife',
    'tags'        => ['Sunset', 'Cliff Diving', 'Cocktails'],
    'emoji'       => '🌅',
    'gradient'    => 'linear-gradient(135deg,#7B2D00,#C4520A)',
    'short_desc'  => "Iconic Negril cliffside bar with world-famous cliff divers, live reggae, and the most stunning Caribbean sunset.",
    'description' => "Perched dramatically on Negril's West End cliffs, Rick's Café has been Jamaica's most legendary hangout since 1974. As the sun descends into the Caribbean, fearless cliff divers leap from heights up to 35 feet while you sip rum cocktails and sway to live reggae. The fiery colors painting the sky behind the divers make for one of the most photographed moments in the entire Caribbean. This package includes round-trip transport from Montego Bay, your entry, a welcome cocktail, and dinner reservation support.",
    'price'       => 95,
    'duration'    => '6 hrs',
    'max_guests'  => 14,
    'location'    => 'Negril',
    'includes'    => ['Round-trip AC transport','Entry & welcome cocktail','Cliff diving show','Live reggae','Sunset viewing'],
    'popular'     => true,
    'difficulty'  => 'Easy',
    'min_age'     => 5,
  ],
  [
    'slug'        => 'atv-mountain-trail',
    'name'        => 'ATV Mountain Adventure',
    'category'    => 'adventure',
    'tags'        => ['ATV', 'Offroad', 'Mud & Thrills'],
    'emoji'       => '🏍️',
    'gradient'    => 'linear-gradient(135deg,#1A3A0A,#2D6E1A)',
    'short_desc'  => "Tear through jungle trails, river crossings, and mountain ridges on powerful 4x4 ATVs with panoramic island views.",
    'description' => "Strap on your helmet and hit the throttle — this is Jamaica's most exhilarating off-road experience. Your certified guide leads you through dense rainforest canopy, muddy river crossings, and along ridge-line trails with sweeping views of the ocean and valleys below. Suitable for beginners and experienced riders alike. All safety gear provided. Get ready to arrive back covered in mud and grinning ear to ear.",
    'price'       => 120,
    'duration'    => '3 hrs',
    'max_guests'  => 12,
    'location'    => 'Montego Bay Hills',
    'includes'    => ['ATV & helmet','Safety briefing','Expert trail guide','Bottled water','Hotel pickup'],
    'popular'     => true,
    'difficulty'  => 'Moderate',
    'min_age'     => 16,
  ],
  [
    'slug'        => 'martha-brae-rafting',
    'name'        => 'Martha Brae River Rafting',
    'category'    => 'rafting',
    'tags'        => ['Rafting', 'Scenic', 'Romantic'],
    'emoji'       => '🚣',
    'gradient'    => 'linear-gradient(135deg,#0A2A3A,#1A5E7A)',
    'short_desc'  => "Glide down the serene Martha Brae River on a hand-crafted bamboo raft, guided by a skilled local rafter through lush jungle.",
    'description' => "The Martha Brae River offers one of Jamaica's most beloved and romantic experiences. Board a traditional hand-crafted bamboo raft and let your expert rafter pole you gently downstream through a canopy of tropical trees and exotic flowers. Couples can sit together on the two-seater raft as you wind through 4 kilometres of emerald river. There's no rush — this is Jamaica at its most serene. A cold Red Stripe beer awaits at the end of your journey.",
    'price'       => 75,
    'duration'    => '2 hrs',
    'max_guests'  => 2,
    'location'    => 'Falmouth',
    'includes'    => ['Bamboo raft ride','Certified rafter guide','Cold drinks at finish','Village walk','Transport from MoBay'],
    'popular'     => true,
    'difficulty'  => 'Easy',
    'min_age'     => 3,
  ],
  [
    'slug'        => 'dunns-river-falls',
    'name'        => "Dunn's River Falls Climb",
    'category'    => 'water',
    'tags'        => ['Waterfall', 'Swimming', 'Iconic'],
    'emoji'       => '🏞️',
    'gradient'    => 'linear-gradient(135deg,#0A2A35,#0D4A3A)',
    'short_desc'  => "Climb Jamaica's most iconic 600-foot terraced waterfall hand-in-hand with your group — a true bucket-list moment.",
    'description' => "Dunn's River Falls in Ocho Rios is arguably the most famous natural landmark in Jamaica — and for good reason. Your group forms a human chain and climbs hand-in-hand up the natural limestone terraces of this spectacular 600-foot waterfall, with the cool fresh water rushing over you at every step. Between climbs, swim in the natural pools carved into the rock. Our certified guides handle all the safety details so you can focus on the pure joy of the experience.",
    'price'       => 89,
    'duration'    => '5 hrs',
    'max_guests'  => 14,
    'location'    => 'Ocho Rios',
    'includes'    => ['Entrance fees','Certified climb guide','Water shoes rental','Fresh coconut water','AC transport'],
    'popular'     => true,
    'difficulty'  => 'Moderate',
    'min_age'     => 6,
  ],
  [
    'slug'        => 'luminous-lagoon',
    'name'        => 'Luminous Lagoon Night Swim',
    'category'    => 'water',
    'tags'        => ['Bioluminescence', 'Night', 'Magical'],
    'emoji'       => '✨',
    'gradient'    => 'linear-gradient(135deg,#050A2A,#0D1A5A)',
    'short_desc'  => "Swim in glowing bioluminescent waters at Falmouth's magical lagoon — your body lights up the sea in electric blue.",
    'description' => "Falmouth's Luminous Lagoon is one of only a handful of places on Earth where bioluminescent microorganisms are so dense that every movement in the water creates a dazzling blue-green glow. Board our boat at dusk and glide across the lagoon as it begins to shimmer. Dive in and watch your arms and legs leave trails of living light. Completely safe, completely otherworldly. Often described by guests as the most surreal and magical experience of their entire life.",
    'price'       => 70,
    'duration'    => '2.5 hrs',
    'max_guests'  => 12,
    'location'    => 'Falmouth',
    'includes'    => ['Boat transfer','Night swim session','Safety flotation','Expert guide narration','Transport from MoBay'],
    'popular'     => false,
    'difficulty'  => 'Easy',
    'min_age'     => 5,
  ],
  [
    'slug'        => 'blue-mountain-hike',
    'name'        => 'Blue Mountain Coffee Trek',
    'category'    => 'nature',
    'tags'        => ['Hiking', 'Coffee', 'Scenic'],
    'emoji'       => '⛰️',
    'gradient'    => 'linear-gradient(135deg,#1A3A0A,#3A5A1A)',
    'short_desc'  => "Hike misty coffee estates high above Kingston, taste the world's finest coffee at its source, and summit Blue Mountain Peak.",
    'description' => "Blue Mountain coffee is considered among the finest in the world, and tasting it fresh from the estate at 7,000 feet above sea level is an experience like no other. This full-day trek takes you through lush montane forest, past hummingbirds and exotic flora, to working coffee estates where you'll learn the entire process from cherry to cup. The mist rolling through the peaks, the birdsong, and that first sip of perfectly brewed coffee at the summit — unforgettable.",
    'price'       => 110,
    'duration'    => '8 hrs',
    'max_guests'  => 8,
    'location'    => 'Blue Mountains',
    'includes'    => ['Expert hiking guide','Coffee cupping session','Breakfast & Jamaican lunch','Transport from Kingston or MoBay','National Park fees'],
    'popular'     => false,
    'difficulty'  => 'Challenging',
    'min_age'     => 12,
  ],
  [
    'slug'        => 'appleton-rum-tour',
    'name'        => 'Appleton Estate Rum Tour',
    'category'    => 'food',
    'tags'        => ['Rum', 'Distillery', 'Tasting'],
    'emoji'       => '🥃',
    'gradient'    => 'linear-gradient(135deg,#3A1A00,#7A3A0A)',
    'short_desc'  => "Tour the historic Appleton Estate distillery in Nassau Valley — featuring an 8-rum tasting flight and cocktail masterclass.",
    'description' => "Deep in the Nassau Valley, surrounded by sugarcane fields, the Appleton Estate has been crafting world-class rum since 1749. Walk through the historic distillery, learn how Jamaican rum gets its distinctive character, and then settle in for a guided tasting of 8 premium rums — from light blends to aged 21-year expressions. A resident mixologist then leads you through a cocktail making session, and lunch is served Jamaican-style with jerk chicken and festival.",
    'price'       => 115,
    'duration'    => '5 hrs',
    'max_guests'  => 14,
    'location'    => 'Nassau Valley',
    'includes'    => ['Distillery tour','8-rum tasting flight','Cocktail masterclass','Jamaican lunch buffet','Souvenir bottle','Round-trip transport'],
    'popular'     => false,
    'difficulty'  => 'Easy',
    'min_age'     => 18,
  ],
  [
    'slug'        => 'horseback-beach-ride',
    'name'        => 'Horseback Ride & Ocean Swim',
    'category'    => 'adventure',
    'tags'        => ['Horseback', 'Beach', 'Ocean'],
    'emoji'       => '🐴',
    'gradient'    => 'linear-gradient(135deg,#2A1A0A,#5A3A1A)',
    'short_desc'  => "Ride gentle horses through lush trails down to a hidden beach, then wade and swim with your horse in the warm Caribbean Sea.",
    'description' => "This is a Jamaican bucket-list classic. Saddle up and ride through tropical trails alongside your guide and gentle horses, eventually breaking out onto a pristine stretch of Caribbean beach. Walk your horse into the warm, crystal-clear water and ride through the waves. Horses are calm and well-trained, suitable for all experience levels. Finish with a picnic by the sea and a cold drink. Absolutely magical, completely unforgettable.",
    'price'       => 85,
    'duration'    => '3 hrs',
    'max_guests'  => 10,
    'location'    => 'Montego Bay',
    'includes'    => ['Horse & riding equipment','Trail & beach ride','Ocean swim session','Cold drinks','Snack by the sea','Hotel pickup'],
    'popular'     => true,
    'difficulty'  => 'Easy',
    'min_age'     => 8,
  ],
  [
    'slug'        => 'negril-snorkeling',
    'name'        => 'Negril Snorkeling & Coral Reef',
    'category'    => 'water',
    'tags'        => ['Snorkeling', 'Coral Reef', 'Marine Life'],
    'emoji'       => '🤿',
    'gradient'    => 'linear-gradient(135deg,#0A1A3A,#0A3A5A)',
    'short_desc'  => "Discover Negril's spectacular coral gardens teeming with tropical fish, sea turtles, and rays just offshore.",
    'description' => "Negril's offshore reef system is one of Jamaica's best-kept secrets — crystal-clear water, rainbow-coloured coral, and an abundance of marine life including green sea turtles, moray eels, sergeant majors, and the occasional nurse shark. Your PADI-certified marine guide leads small groups on a 2-hour reef exploration, with equipment included. First-timers are given full instruction. This tour also includes a stop at a private sandbar for swimming.",
    'price'       => 78,
    'duration'    => '3 hrs',
    'max_guests'  => 10,
    'location'    => 'Negril',
    'includes'    => ['Full snorkel gear','PADI-certified guide','Sandbar swim stop','Marine ID card','Fresh fruit & water','Boat transfer'],
    'popular'     => false,
    'difficulty'  => 'Easy',
    'min_age'     => 8,
  ],
  [
    'slug'        => 'reggae-culture-kingston',
    'name'        => "Reggae & Culture: Kingston Deep Dive",
    'category'    => 'culture',
    'tags'        => ['Reggae', 'Bob Marley', 'History'],
    'emoji'       => '🎵',
    'gradient'    => 'linear-gradient(135deg,#1A1A0A,#3A3A0A)',
    'short_desc'  => "Walk in Bob Marley's footsteps through Trench Town, Tuff Gong Studios, and the Bob Marley Museum — reggae at its roots.",
    'description' => "Kingston is the soul of Jamaica — the birthplace of reggae, ska, and dancehall music that changed the world. This cultural immersion tour takes you deep into the city's storied neighbourhoods and music history. Visit the Bob Marley Museum on Hope Road, walk through Trench Town where it all began, tour Tuff Gong Recording Studios (still in operation), enjoy a jerk lunch in a local yard, and end with a sound system session at a community centre. Real Kingston. Real story.",
    'price'       => 98,
    'duration'    => '7 hrs',
    'max_guests'  => 10,
    'location'    => 'Kingston',
    'includes'    => ['Museum entry','Studio tour','Trench Town walk','Jerk chicken lunch','Sound system session','Transport'],
    'popular'     => false,
    'difficulty'  => 'Easy',
    'min_age'     => 10,
  ],
  [
    'slug'        => 'black-river-safari',
    'name'        => 'Black River Crocodile Safari',
    'category'    => 'nature',
    'tags'        => ['Wildlife', 'Boat Safari', 'Crocodiles'],
    'emoji'       => '🐊',
    'gradient'    => 'linear-gradient(135deg,#0A2A0A,#1A4A0A)',
    'short_desc'  => "Glide through Jamaica's longest river on a flat-bottom boat, spotting wild crocodiles, herons, and rare mangrove birds.",
    'description' => "The Black River is Jamaica's longest and most biodiverse waterway — a UNESCO-designated wetland teeming with wildlife. Board a flat-bottom safari boat and navigate through ancient mangrove tunnels while your naturalist guide points out American crocodiles basking on the banks, snowy egrets, jacanas, and over 100 bird species. The tour also visits a local fishing village where you can interact with residents and try fresh seafood. An extraordinary wildlife encounter right in Jamaica's backyard.",
    'price'       => 85,
    'duration'    => '4 hrs',
    'max_guests'  => 12,
    'location'    => 'Black River, St. Elizabeth',
    'includes'    => ['Guided boat safari','Naturalist commentary','Village visit','Fresh seafood lunch','Transport from MoBay'],
    'popular'     => false,
    'difficulty'  => 'Easy',
    'min_age'     => 5,
  ],
  [
    'slug'        => 'ys-falls-zipline',
    'name'        => 'YS Falls & Zip-line Combo',
    'category'    => 'adventure',
    'tags'        => ['Waterfall', 'Zip-line', 'Swimming'],
    'emoji'       => '🌊',
    'gradient'    => 'linear-gradient(135deg,#0A2A1A,#1A5A2A)',
    'short_desc'  => "Swim in the multi-tiered YS Falls, then zip-line across the river gorge — one of Jamaica's finest adventure combos.",
    'description' => "YS Falls is Jamaica's most beautiful lesser-known waterfall — seven cascading tiers set in the lush St. Elizabeth countryside, fed by crystal-clear spring water. After swimming and jumping the tiers, strap into a harness and zip-line across the river gorge above the falls for an adrenaline rush with a breathtaking view. The private estate setting means it never feels crowded. Finish with a buffet lunch on the estate terrace. This is the perfect day.",
    'price'       => 125,
    'duration'    => '6 hrs',
    'max_guests'  => 12,
    'location'    => 'St. Elizabeth',
    'includes'    => ['YS Falls entry','Zip-line ride','Swimming time','Estate lunch buffet','Life jackets','Round-trip transport'],
    'popular'     => true,
    'difficulty'  => 'Moderate',
    'min_age'     => 10,
  ],
];
?>
